
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Computadora
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        DB.Conection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Administrator = new javax.swing.JFrame();
        jTabbedPane_Admin = new javax.swing.JTabbedPane();
        Student = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        StudentID = new javax.swing.JTextField();
        StudentName = new javax.swing.JTextField();
        StudentPhoneNumber = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_Students = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        StudentAdress = new javax.swing.JTextField();
        jButton_AddStudent = new javax.swing.JButton();
        jButton_ModifyStudent = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jText_StudentSearchID = new javax.swing.JTextField();
        jButton_RefreshStudent = new javax.swing.JButton();
        jButton_SearchStudent = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        StudentLastName = new javax.swing.JTextField();
        Professor = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jText_AppointmentClientID = new javax.swing.JTextField();
        jText_AppointmentClientName = new javax.swing.JTextField();
        jText_AppointmentClientPhoneNumber = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable_AppointmentAssesor = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jText_AppointmentAssesorID = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jText_AppointmentAssesorName = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable_AppointmentAutomobile = new javax.swing.JTable();
        jLabel42 = new javax.swing.JLabel();
        jText_AppointmentClientSearchID = new javax.swing.JTextField();
        jButton_AppointmentSearchClient = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jText_AppointmentAssesorPhoneNumber = new javax.swing.JTextField();
        jText_AppointmentPlate = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jText_AppointmentModel = new javax.swing.JTextField();
        jText_AppointmentMotor = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jComboBox_AppointmentType = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jButton_AddStudent3 = new javax.swing.JButton();
        jButton_ModifyStudent3 = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        jText_AppointmentAssesorID1 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jText_AppointmentAssesorName1 = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jText_AppointmentAssesorPhoneNumber1 = new javax.swing.JTextField();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable_AppointmentAssesor1 = new javax.swing.JTable();
        jButton_AddStudent4 = new javax.swing.JButton();
        jButton_AddStudent5 = new javax.swing.JButton();
        jButton_AddStudent6 = new javax.swing.JButton();
        Test_Class = new javax.swing.JPanel();
        jButton_SearchEmployee = new javax.swing.JButton();
        jButton_AddEmployee = new javax.swing.JButton();
        jButton_ModifyEmployee = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jText_UserName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jText_Name = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jText_ID = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jText_PhoneNumber = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Employees = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jCombo_EmployeeType = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jButton_RefreshEmployee = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jText_EmployeeSearchID = new javax.swing.JTextField();
        jPopup_DeleteStudent = new javax.swing.JPopupMenu();
        jMenuItem_ViewStudent = new javax.swing.JMenuItem();
        jMenuItem_DeleteStudent = new javax.swing.JMenuItem();
        jPopupMenu_GetData = new javax.swing.JPopupMenu();
        jMenuItem_GetData = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        cb_UserType = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jText_Username = new javax.swing.JTextField();
        jb_loginMain1 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jText_UserPassword = new javax.swing.JTextField();

        jTabbedPane_Admin.setBackground(new java.awt.Color(40, 80, 47));
        jTabbedPane_Admin.setBorder(new javax.swing.border.MatteBorder(null));
        jTabbedPane_Admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane_AdminMouseClicked(evt);
            }
        });

        Student.setBackground(new java.awt.Color(0, 0, 51));
        Student.setBorder(new javax.swing.border.MatteBorder(null));
        Student.setForeground(java.awt.Color.white);
        Student.setToolTipText("");

        jLabel17.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel17.setForeground(java.awt.Color.white);
        jLabel17.setText("Lastname:");

        jLabel18.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel18.setForeground(java.awt.Color.white);
        jLabel18.setText("Name:");

        jLabel19.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel19.setForeground(java.awt.Color.white);
        jLabel19.setText("ID:");

        jLabel21.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel21.setForeground(java.awt.Color.white);
        jLabel21.setText("Phone #:");

        jTable_Students.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_Students.setComponentPopupMenu(jPopup_DeleteStudent);
        jScrollPane4.setViewportView(jTable_Students);

        jLabel22.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel22.setForeground(java.awt.Color.white);
        jLabel22.setText("Address:");

        jButton_AddStudent.setBackground(new java.awt.Color(44, 44, 44));
        jButton_AddStudent.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jButton_AddStudent.setText("Add");
        jButton_AddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddStudentActionPerformed(evt);
            }
        });

        jButton_ModifyStudent.setBackground(new java.awt.Color(44, 44, 44));
        jButton_ModifyStudent.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jButton_ModifyStudent.setText("Modify");
        jButton_ModifyStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ModifyStudentActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel37.setForeground(java.awt.Color.white);
        jLabel37.setText("INPUT STUDENT ID:");

        jButton_RefreshStudent.setBackground(new java.awt.Color(44, 44, 44));
        jButton_RefreshStudent.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jButton_RefreshStudent.setText("Refresh");
        jButton_RefreshStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RefreshStudentActionPerformed(evt);
            }
        });

        jButton_SearchStudent.setBackground(new java.awt.Color(44, 44, 44));
        jButton_SearchStudent.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jButton_SearchStudent.setText("Search");
        jButton_SearchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchStudentActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Registered Students:");

        javax.swing.GroupLayout StudentLayout = new javax.swing.GroupLayout(Student);
        Student.setLayout(StudentLayout);
        StudentLayout.setHorizontalGroup(
            StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 649, Short.MAX_VALUE))
                    .addGroup(StudentLayout.createSequentialGroup()
                        .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StudentLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton_RefreshStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(StudentLayout.createSequentialGroup()
                                        .addComponent(jLabel37)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jText_StudentSearchID)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_SearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(StudentLayout.createSequentialGroup()
                                .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(StudentLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(StudentLayout.createSequentialGroup()
                                                .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel17)
                                                    .addComponent(jLabel19))
                                                .addGap(18, 18, 18)
                                                .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(StudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(StudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(StudentLastName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel18)))
                                    .addGroup(StudentLayout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(jButton_AddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(StudentLayout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(StudentAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(StudentLayout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addGap(18, 18, 18)
                                        .addComponent(StudentPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(StudentLayout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jButton_ModifyStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)))
                        .addGap(17, 17, 17))))
        );
        StudentLayout.setVerticalGroup(
            StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentLayout.createSequentialGroup()
                        .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(StudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(StudentLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)))
                    .addGroup(StudentLayout.createSequentialGroup()
                        .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StudentPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StudentAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))))
                .addGap(37, 37, 37)
                .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_AddStudent)
                    .addComponent(jButton_ModifyStudent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_StudentSearchID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_SearchStudent))
                .addGap(18, 18, 18)
                .addComponent(jButton_RefreshStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        jTabbedPane_Admin.addTab("Student", Student);

        Professor.setBackground(new java.awt.Color(0, 0, 51));
        Professor.setBorder(new javax.swing.border.MatteBorder(null));
        Professor.setForeground(java.awt.Color.white);

        jLabel46.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel46.setForeground(java.awt.Color.white);
        jLabel46.setText("Name:");

        jLabel47.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel47.setForeground(java.awt.Color.white);
        jLabel47.setText("ID:");

        jText_AppointmentClientID.setEnabled(false);

        jText_AppointmentClientName.setEnabled(false);

        jText_AppointmentClientPhoneNumber.setEnabled(false);

        jLabel48.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel48.setForeground(java.awt.Color.white);
        jLabel48.setText("Phone #:");

        jTable_AppointmentAssesor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane8.setViewportView(jTable_AppointmentAssesor);

        jLabel13.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setText("ID:");

        jText_AppointmentAssesorID.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel14.setForeground(java.awt.Color.white);
        jLabel14.setText("Name:");

        jText_AppointmentAssesorName.setEnabled(false);

        jTable_AppointmentAutomobile.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane9.setViewportView(jTable_AppointmentAutomobile);

        jLabel42.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel42.setForeground(java.awt.Color.white);
        jLabel42.setText("INPUT  ID:");

        jButton_AppointmentSearchClient.setBackground(new java.awt.Color(44, 44, 44));
        jButton_AppointmentSearchClient.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        jButton_AppointmentSearchClient.setText("Search");
        jButton_AppointmentSearchClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AppointmentSearchClientActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel15.setForeground(java.awt.Color.white);
        jLabel15.setText("Level:");

        jLabel52.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel52.setForeground(java.awt.Color.white);
        jLabel52.setText("Phone #:");

        jText_AppointmentAssesorPhoneNumber.setEnabled(false);

        jText_AppointmentPlate.setEnabled(false);

        jLabel53.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel53.setForeground(java.awt.Color.white);
        jLabel53.setText("Motor");

        jLabel54.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel54.setForeground(java.awt.Color.white);
        jLabel54.setText("Plate");

        jText_AppointmentModel.setEnabled(false);

        jText_AppointmentMotor.setEnabled(false);

        jLabel55.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel55.setForeground(java.awt.Color.white);
        jLabel55.setText("Model");

        jComboBox_AppointmentType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level I", "Level II", "Level III" }));
        jComboBox_AppointmentType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_AppointmentTypeActionPerformed(evt);
            }
        });

        jButton_AddStudent3.setBackground(new java.awt.Color(44, 44, 44));
        jButton_AddStudent3.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jButton_AddStudent3.setText("Add");
        jButton_AddStudent3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddStudent3ActionPerformed(evt);
            }
        });

        jButton_ModifyStudent3.setBackground(new java.awt.Color(44, 44, 44));
        jButton_ModifyStudent3.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jButton_ModifyStudent3.setText("Modify");
        jButton_ModifyStudent3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ModifyStudent3ActionPerformed(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel43.setForeground(java.awt.Color.white);
        jLabel43.setText("ID:");

        jText_AppointmentAssesorID1.setEnabled(false);

        jLabel44.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel44.setForeground(java.awt.Color.white);
        jLabel44.setText("Name:");

        jText_AppointmentAssesorName1.setEnabled(false);

        jLabel56.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel56.setForeground(java.awt.Color.white);
        jLabel56.setText("Phone #:");

        jText_AppointmentAssesorPhoneNumber1.setEnabled(false);

        jTable_AppointmentAssesor1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane10.setViewportView(jTable_AppointmentAssesor1);

        jButton_AddStudent4.setBackground(new java.awt.Color(44, 44, 44));
        jButton_AddStudent4.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jButton_AddStudent4.setText("Assign Car");
        jButton_AddStudent4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddStudent4ActionPerformed(evt);
            }
        });

        jButton_AddStudent5.setBackground(new java.awt.Color(44, 44, 44));
        jButton_AddStudent5.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jButton_AddStudent5.setText("Assign Test");
        jButton_AddStudent5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddStudent5ActionPerformed(evt);
            }
        });

        jButton_AddStudent6.setBackground(new java.awt.Color(44, 44, 44));
        jButton_AddStudent6.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jButton_AddStudent6.setText("Assign Course");
        jButton_AddStudent6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddStudent6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProfessorLayout = new javax.swing.GroupLayout(Professor);
        Professor.setLayout(ProfessorLayout);
        ProfessorLayout.setHorizontalGroup(
            ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfessorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfessorLayout.createSequentialGroup()
                        .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel46)
                            .addComponent(jLabel47)
                            .addComponent(jLabel48)
                            .addComponent(jLabel15))
                        .addGap(3, 3, 3)
                        .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProfessorLayout.createSequentialGroup()
                                .addComponent(jComboBox_AppointmentType, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(ProfessorLayout.createSequentialGroup()
                                .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ProfessorLayout.createSequentialGroup()
                                        .addComponent(jText_AppointmentClientPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton_ModifyStudent3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ProfessorLayout.createSequentialGroup()
                                        .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jText_AppointmentClientID)
                                            .addComponent(jText_AppointmentClientName, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton_AddStudent3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(149, 149, 149))))
                    .addGroup(ProfessorLayout.createSequentialGroup()
                        .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(ProfessorLayout.createSequentialGroup()
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel55)
                                        .addComponent(jLabel53)
                                        .addGroup(ProfessorLayout.createSequentialGroup()
                                            .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(52, 52, 52)
                                            .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jText_AppointmentPlate, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(ProfessorLayout.createSequentialGroup()
                                                    .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jText_AppointmentModel)
                                                        .addComponent(jText_AppointmentMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                                    .addComponent(jButton_AddStudent4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGroup(ProfessorLayout.createSequentialGroup()
                                    .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(ProfessorLayout.createSequentialGroup()
                                            .addComponent(jLabel42)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jText_AppointmentClientSearchID, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton_AppointmentSearchClient, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(ProfessorLayout.createSequentialGroup()
                                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(ProfessorLayout.createSequentialGroup()
                                                    .addComponent(jLabel52)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                                    .addComponent(jText_AppointmentAssesorPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(ProfessorLayout.createSequentialGroup()
                                                    .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel14)
                                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING))
                                                    .addGap(62, 62, 62)
                                                    .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jText_AppointmentAssesorName, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                                        .addComponent(jText_AppointmentAssesorID))))))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ProfessorLayout.createSequentialGroup()
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(ProfessorLayout.createSequentialGroup()
                                        .addComponent(jLabel56)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jText_AppointmentAssesorPhoneNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ProfessorLayout.createSequentialGroup()
                                        .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel44)
                                            .addComponent(jLabel43, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(62, 62, 62)
                                        .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jText_AppointmentAssesorName1)
                                            .addComponent(jText_AppointmentAssesorID1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(41, 41, 41)
                                .addComponent(jButton_AddStudent5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ProfessorLayout.createSequentialGroup()
                    .addGap(656, 656, 656)
                    .addComponent(jButton_AddStudent6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(11, 11, 11)))
        );
        ProfessorLayout.setVerticalGroup(
            ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfessorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_AppointmentClientSearchID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_AppointmentSearchClient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfessorLayout.createSequentialGroup()
                        .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel46)
                            .addComponent(jText_AppointmentClientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jText_AppointmentClientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel47)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfessorLayout.createSequentialGroup()
                        .addComponent(jButton_AddStudent3)
                        .addGap(8, 8, 8)))
                .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_AppointmentClientPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48)
                    .addComponent(jButton_ModifyStudent3))
                .addGap(18, 18, 18)
                .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jComboBox_AppointmentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfessorLayout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfessorLayout.createSequentialGroup()
                        .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel54)
                            .addComponent(jText_AppointmentPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel55)
                            .addComponent(jText_AppointmentModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_AddStudent4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel53)
                            .addComponent(jText_AppointmentMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)))
                .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ProfessorLayout.createSequentialGroup()
                        .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jText_AppointmentAssesorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jText_AppointmentAssesorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel52)
                            .addComponent(jText_AppointmentAssesorPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)))
                .addGap(18, 18, 18)
                .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ProfessorLayout.createSequentialGroup()
                        .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44)
                            .addComponent(jText_AppointmentAssesorName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jText_AppointmentAssesorID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43)
                            .addComponent(jButton_AddStudent5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel56)
                            .addComponent(jText_AppointmentAssesorPhoneNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfessorLayout.createSequentialGroup()
                    .addContainerGap(455, Short.MAX_VALUE)
                    .addComponent(jButton_AddStudent6)
                    .addGap(218, 218, 218)))
        );

        jTabbedPane_Admin.addTab("Proffesor", Professor);

        Test_Class.setBackground(new java.awt.Color(0, 0, 51));
        Test_Class.setBorder(new javax.swing.border.MatteBorder(null));
        Test_Class.setForeground(java.awt.Color.white);

        jButton_SearchEmployee.setBackground(new java.awt.Color(44, 44, 44));
        jButton_SearchEmployee.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jButton_SearchEmployee.setForeground(java.awt.Color.white);
        jButton_SearchEmployee.setText("Search");
        jButton_SearchEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchEmployeeActionPerformed(evt);
            }
        });

        jButton_AddEmployee.setBackground(new java.awt.Color(44, 44, 44));
        jButton_AddEmployee.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jButton_AddEmployee.setForeground(java.awt.Color.white);
        jButton_AddEmployee.setText("Add");
        jButton_AddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddEmployeeActionPerformed(evt);
            }
        });

        jButton_ModifyEmployee.setBackground(new java.awt.Color(44, 44, 44));
        jButton_ModifyEmployee.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jButton_ModifyEmployee.setForeground(java.awt.Color.white);
        jButton_ModifyEmployee.setText("Modify");
        jButton_ModifyEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ModifyEmployeeActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("Username:");

        jLabel12.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setText("Name:");

        jLabel16.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel16.setForeground(java.awt.Color.white);
        jLabel16.setText("ID:");

        jLabel23.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel23.setForeground(java.awt.Color.white);
        jLabel23.setText("Phone #:");

        jTable_Employees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable_Employees);

        jLabel24.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel24.setForeground(java.awt.Color.white);
        jLabel24.setText("Type:");

        jCombo_EmployeeType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mechanic", "Assessor" }));

        jLabel29.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel29.setForeground(java.awt.Color.white);
        jLabel29.setText("Registered Employees:");

        jButton_RefreshEmployee.setBackground(new java.awt.Color(44, 44, 44));
        jButton_RefreshEmployee.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jButton_RefreshEmployee.setForeground(java.awt.Color.white);
        jButton_RefreshEmployee.setText("Refresh");
        jButton_RefreshEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RefreshEmployeeActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel30.setForeground(java.awt.Color.white);
        jLabel30.setText("INPUT EMPLOYEE ID:");

        javax.swing.GroupLayout Test_ClassLayout = new javax.swing.GroupLayout(Test_Class);
        Test_Class.setLayout(Test_ClassLayout);
        Test_ClassLayout.setHorizontalGroup(
            Test_ClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Test_ClassLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(Test_ClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addGroup(Test_ClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(Test_ClassLayout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addGroup(Test_ClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(Test_ClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(jLabel11)
                                .addComponent(jLabel23))
                            .addGroup(Test_ClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jText_PhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(Test_ClassLayout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(Test_ClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jText_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(Test_ClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jText_Name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jText_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGap(190, 190, 190)
                            .addGroup(Test_ClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton_AddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_ModifyEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(Test_ClassLayout.createSequentialGroup()
                                    .addComponent(jLabel24)
                                    .addGap(18, 18, 18)
                                    .addComponent(jCombo_EmployeeType, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(Test_ClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(Test_ClassLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jText_EmployeeSearchID)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_SearchEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton_RefreshEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        Test_ClassLayout.setVerticalGroup(
            Test_ClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Test_ClassLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(Test_ClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Test_ClassLayout.createSequentialGroup()
                        .addGroup(Test_ClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jText_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Test_ClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jText_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(20, 20, 20)
                        .addGroup(Test_ClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jText_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)))
                    .addGroup(Test_ClassLayout.createSequentialGroup()
                        .addGroup(Test_ClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCombo_EmployeeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addComponent(jButton_AddEmployee)
                        .addGap(17, 17, 17)
                        .addComponent(jButton_ModifyEmployee)))
                .addGap(18, 18, 18)
                .addGroup(Test_ClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(26, 26, 26)
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Test_ClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_SearchEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jText_EmployeeSearchID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton_RefreshEmployee)
                .addGap(69, 69, 69))
        );

        jTabbedPane_Admin.addTab("More", Test_Class);

        javax.swing.GroupLayout AdministratorLayout = new javax.swing.GroupLayout(Administrator.getContentPane());
        Administrator.getContentPane().setLayout(AdministratorLayout);
        AdministratorLayout.setHorizontalGroup(
            AdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_Admin)
        );
        AdministratorLayout.setVerticalGroup(
            AdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_Admin)
        );

        jMenuItem_ViewStudent.setText("Quick View");
        jMenuItem_ViewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ViewStudentActionPerformed(evt);
            }
        });
        jPopup_DeleteStudent.add(jMenuItem_ViewStudent);

        jMenuItem_DeleteStudent.setText("DeleteEmployee");
        jMenuItem_DeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_DeleteStudentActionPerformed(evt);
            }
        });
        jPopup_DeleteStudent.add(jMenuItem_DeleteStudent);

        jMenuItem_GetData.setText("See Data");
        jMenuItem_GetData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_GetDataActionPerformed(evt);
            }
        });
        jPopupMenu_GetData.add(jMenuItem_GetData);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        cb_UserType.setFont(new java.awt.Font("TlwgTypewriter", 0, 15)); // NOI18N
        cb_UserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrator", "Student", "Professor" }));

        jLabel8.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("User Type: ");

        jLabel9.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Username:");

        jLabel10.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Password:");

        jb_loginMain1.setBackground(new java.awt.Color(44, 44, 44));
        jb_loginMain1.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jb_loginMain1.setText("Login");
        jb_loginMain1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_loginMain1ActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel27.setForeground(java.awt.Color.white);
        jLabel27.setText("NOTE: *Student login requires a registered account.");

        jLabel28.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel28.setForeground(java.awt.Color.white);
        jLabel28.setText("*Teacher login requires password granted by local admin.");

        jLabel34.setFont(new java.awt.Font("TlwgTypewriter", 1, 24)); // NOI18N
        jLabel34.setForeground(java.awt.Color.white);
        jLabel34.setText("General Login");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel34))
                    .addComponent(jLabel28)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel27)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jb_loginMain1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jText_UserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(23, 23, 23)
                                            .addComponent(jText_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addComponent(cb_UserType, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(11, 11, 11))))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cb_UserType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jText_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jText_UserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_loginMain1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_loginMain1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_loginMain1ActionPerformed
        String UserType = (String) cb_UserType.getSelectedItem();
        String UserName = jText_Username.getText();
        String Password = jText_UserPassword.getText();
        if (DB.VerifyUser(UserName,Password)) {
            String tipo = "";
            if (UserType.equals("Administrator")) {
                Administrator.setVisible(true);
                Administrator.pack();
            }else if (UserType.equals("Student")) {
                
            }
       
        } else {
            JOptionPane.showMessageDialog(this, "Incorrect Password or Username");
        }
            
    }//GEN-LAST:event_jb_loginMain1ActionPerformed

    private void jButton_AddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddStudentActionPerformed
        DB.AddStudentDocument(StudentID.getText(),StudentName.getText(),StudentLastName.getText(),StudentPhoneNumber.getText(),StudentAdress.getText());
        JOptionPane.showMessageDialog(this, "Stundent Created Successfully!");
    }//GEN-LAST:event_jButton_AddStudentActionPerformed
    private void jButton_ModifyStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ModifyStudentActionPerformed
       DB.ModifyStudentDocument(StudentID.getText(),StudentName.getText(),StudentLastName.getText(),StudentPhoneNumber.getText(),StudentAdress.getText());
       JOptionPane.showMessageDialog(this, "Stundent Modified Successfully!");
    }//GEN-LAST:event_jButton_ModifyStudentActionPerformed
    private void jButton_RefreshStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RefreshStudentActionPerformed
            DefaultTableModel Modelo = new DefaultTableModel();
            Modelo.addColumn("ID");
            Modelo.addColumn("Name");
            Modelo.addColumn("LastName");
            Modelo.addColumn("PhoneNumber");
            Modelo.addColumn("Student Adress");
            jTable_Students.setModel(DB.GetAllDocuments(Modelo));
    }//GEN-LAST:event_jButton_RefreshStudentActionPerformed

    private void jButton_SearchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchStudentActionPerformed
       
    }//GEN-LAST:event_jButton_SearchStudentActionPerformed

    private void jButton_AppointmentSearchClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AppointmentSearchClientActionPerformed
        
    }//GEN-LAST:event_jButton_AppointmentSearchClientActionPerformed

    private void jComboBox_AppointmentTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_AppointmentTypeActionPerformed
       
    }//GEN-LAST:event_jComboBox_AppointmentTypeActionPerformed

    private void jButton_SearchEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchEmployeeActionPerformed
        
    }//GEN-LAST:event_jButton_SearchEmployeeActionPerformed

    private void jButton_AddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddEmployeeActionPerformed
        
    }//GEN-LAST:event_jButton_AddEmployeeActionPerformed

    private void jButton_ModifyEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ModifyEmployeeActionPerformed
        
    }//GEN-LAST:event_jButton_ModifyEmployeeActionPerformed

    private void jButton_RefreshEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RefreshEmployeeActionPerformed
        
    }//GEN-LAST:event_jButton_RefreshEmployeeActionPerformed

    private void jTabbedPane_AdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane_AdminMouseClicked

    }//GEN-LAST:event_jTabbedPane_AdminMouseClicked

    private void jMenuItem_ViewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ViewStudentActionPerformed
        
    }//GEN-LAST:event_jMenuItem_ViewStudentActionPerformed

    private void jMenuItem_DeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_DeleteStudentActionPerformed
        int Row=jTable_Students.getSelectedRow();                
        String IDtoErase=jTable_Students.getValueAt(Row,0).toString();
        DB.DeleteStudentDocument(IDtoErase);
        JOptionPane.showMessageDialog(this, "Stundent Deleted Successfully!");
    }//GEN-LAST:event_jMenuItem_DeleteStudentActionPerformed

    private void jMenuItem_GetDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_GetDataActionPerformed
        int Row = jTable_AppointmentAutomobile.getSelectedRow();
        jText_AppointmentPlate.setText(jTable_AppointmentAutomobile.getValueAt(Row, 0).toString());
        jText_AppointmentModel.setText(jTable_AppointmentAutomobile.getValueAt(Row, 1).toString());
        jText_AppointmentMotor.setText(jTable_AppointmentAutomobile.getValueAt(Row, 2).toString());
    }//GEN-LAST:event_jMenuItem_GetDataActionPerformed

    private void jButton_AddStudent3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddStudent3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_AddStudent3ActionPerformed

    private void jButton_ModifyStudent3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ModifyStudent3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ModifyStudent3ActionPerformed

    private void jButton_AddStudent4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddStudent4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_AddStudent4ActionPerformed

    private void jButton_AddStudent5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddStudent5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_AddStudent5ActionPerformed

    private void jButton_AddStudent6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddStudent6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_AddStudent6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Administrator;
    private javax.swing.JPanel Professor;
    private javax.swing.JPanel Student;
    private javax.swing.JPanel Student1;
    private javax.swing.JPanel Student2;
    private javax.swing.JTextField StudentAdress;
    private javax.swing.JTextField StudentAdress1;
    private javax.swing.JTextField StudentAdress2;
    private javax.swing.JTextField StudentID;
    private javax.swing.JTextField StudentID1;
    private javax.swing.JTextField StudentID2;
    private javax.swing.JTextField StudentLastName;
    private javax.swing.JTextField StudentLastName1;
    private javax.swing.JTextField StudentLastName2;
    private javax.swing.JTextField StudentName;
    private javax.swing.JTextField StudentName1;
    private javax.swing.JTextField StudentName2;
    private javax.swing.JTextField StudentPhoneNumber;
    private javax.swing.JTextField StudentPhoneNumber1;
    private javax.swing.JTextField StudentPhoneNumber2;
    private javax.swing.JPanel Test_Class;
    private javax.swing.JComboBox<String> cb_UserType;
    private javax.swing.JButton jButton_AddEmployee;
    private javax.swing.JButton jButton_AddStudent;
    private javax.swing.JButton jButton_AddStudent1;
    private javax.swing.JButton jButton_AddStudent2;
    private javax.swing.JButton jButton_AddStudent3;
    private javax.swing.JButton jButton_AddStudent4;
    private javax.swing.JButton jButton_AddStudent5;
    private javax.swing.JButton jButton_AddStudent6;
    private javax.swing.JButton jButton_AppointmentSearchClient;
    private javax.swing.JButton jButton_ModifyEmployee;
    private javax.swing.JButton jButton_ModifyStudent;
    private javax.swing.JButton jButton_ModifyStudent1;
    private javax.swing.JButton jButton_ModifyStudent2;
    private javax.swing.JButton jButton_ModifyStudent3;
    private javax.swing.JButton jButton_RefreshEmployee;
    private javax.swing.JButton jButton_RefreshStudent;
    private javax.swing.JButton jButton_RefreshStudent1;
    private javax.swing.JButton jButton_RefreshStudent2;
    private javax.swing.JButton jButton_SearchEmployee;
    private javax.swing.JButton jButton_SearchStudent;
    private javax.swing.JButton jButton_SearchStudent1;
    private javax.swing.JButton jButton_SearchStudent2;
    private javax.swing.JComboBox<String> jComboBox_AppointmentType;
    private javax.swing.JComboBox<String> jCombo_EmployeeType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem_DeleteStudent;
    private javax.swing.JMenuItem jMenuItem_GetData;
    private javax.swing.JMenuItem jMenuItem_ViewStudent;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu_GetData;
    private javax.swing.JPopupMenu jPopup_DeleteStudent;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane_Admin;
    private javax.swing.JTabbedPane jTabbedPane_Admin1;
    private javax.swing.JTabbedPane jTabbedPane_Admin2;
    private javax.swing.JTable jTable_AppointmentAssesor;
    private javax.swing.JTable jTable_AppointmentAssesor1;
    private javax.swing.JTable jTable_AppointmentAutomobile;
    private javax.swing.JTable jTable_Employees;
    private javax.swing.JTable jTable_Students;
    private javax.swing.JTable jTable_Students1;
    private javax.swing.JTable jTable_Students2;
    private javax.swing.JTextField jText_AppointmentAssesorID;
    private javax.swing.JTextField jText_AppointmentAssesorID1;
    private javax.swing.JTextField jText_AppointmentAssesorName;
    private javax.swing.JTextField jText_AppointmentAssesorName1;
    private javax.swing.JTextField jText_AppointmentAssesorPhoneNumber;
    private javax.swing.JTextField jText_AppointmentAssesorPhoneNumber1;
    private javax.swing.JTextField jText_AppointmentClientID;
    private javax.swing.JTextField jText_AppointmentClientName;
    private javax.swing.JTextField jText_AppointmentClientPhoneNumber;
    private javax.swing.JTextField jText_AppointmentClientSearchID;
    private javax.swing.JTextField jText_AppointmentModel;
    private javax.swing.JTextField jText_AppointmentMotor;
    private javax.swing.JTextField jText_AppointmentPlate;
    private javax.swing.JTextField jText_EmployeeSearchID;
    private javax.swing.JTextField jText_ID;
    private javax.swing.JTextField jText_Name;
    private javax.swing.JTextField jText_PhoneNumber;
    private javax.swing.JTextField jText_StudentSearchID;
    private javax.swing.JTextField jText_StudentSearchID1;
    private javax.swing.JTextField jText_StudentSearchID2;
    private javax.swing.JTextField jText_UserName;
    private javax.swing.JTextField jText_UserPassword;
    private javax.swing.JTextField jText_Username;
    private javax.swing.JButton jb_loginMain1;
    // End of variables declaration//GEN-END:variables
    String AdminUsername="Juana";
    String AdminPassword="123";
    ConnectToDB DB=new ConnectToDB();
        
}
