
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Computadora
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        DB.Conection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Administrator = new javax.swing.JFrame();
        jTabbedPane_Admin = new javax.swing.JTabbedPane();
        Student = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        StudentID = new javax.swing.JTextField();
        StudentName = new javax.swing.JTextField();
        StudentPhoneNumber = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_Students = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        StudentAdress = new javax.swing.JTextField();
        jButton_AddStudent = new javax.swing.JButton();
        jButton_ModifyStudent = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jText_StudentSearchID = new javax.swing.JTextField();
        jButton_RefreshStudent = new javax.swing.JButton();
        jButton_SearchStudent = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        StudentLastName = new javax.swing.JTextField();
        Professor = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        TeacherID = new javax.swing.JTextField();
        TeacherName = new javax.swing.JTextField();
        TeacherPhoneNumber = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable_AssignCourse = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        AssignCourseID = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable_AssignCar = new javax.swing.JTable();
        jLabel42 = new javax.swing.JLabel();
        SearchTeacherID = new javax.swing.JTextField();
        SearchTeacher = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        AssignCarPlate = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        AssigCarKilometers = new javax.swing.JTextField();
        TeacherLevel = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        AddTeacher = new javax.swing.JButton();
        ModifyTeacher = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        AssignTestID = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable_AssignTest = new javax.swing.JTable();
        AssignCar = new javax.swing.JButton();
        jButton_AddStudent5 = new javax.swing.JButton();
        AssignCourse = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        AssignCourseLevel = new javax.swing.JComboBox<>();
        AssignCourseType = new javax.swing.JComboBox<>();
        AssignTestLevel = new javax.swing.JComboBox<>();
        AssignTestType = new javax.swing.JComboBox<>();
        Test_Class = new javax.swing.JPanel();
        jPopup_DeleteStudent = new javax.swing.JPopupMenu();
        jMenuItem_ViewStudent = new javax.swing.JMenuItem();
        jMenuItem_DeleteStudent = new javax.swing.JMenuItem();
        jPopupMenu_GetData = new javax.swing.JPopupMenu();
        jMenuItem_GetData = new javax.swing.JMenuItem();
        StudentJFrame = new javax.swing.JFrame();
        jTabbedPane_Admin1 = new javax.swing.JTabbedPane();
        Student1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        StudentIDStudent = new javax.swing.JTextField();
        StudentNameStudent = new javax.swing.JTextField();
        StudentPhoneNumberStudent = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable_Classes_Students = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        StudentAdressStudent = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        StudentLastNameStudent = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable_Licenses_Students = new javax.swing.JTable();
        Professor1 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        AssignTestID1 = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTable_AssignTest1 = new javax.swing.JTable();
        jButton_AddStudent6 = new javax.swing.JButton();
        AssignCourse1 = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        AssignTestLevel1 = new javax.swing.JComboBox<>();
        AssignTestType1 = new javax.swing.JComboBox<>();
        Combo_EnrollClasses = new javax.swing.JComboBox<>();
        jLabel57 = new javax.swing.JLabel();
        Combo_EnrollTeachers = new javax.swing.JComboBox<>();
        jLabel58 = new javax.swing.JLabel();
        ClassCostStudent = new javax.swing.JTextField();
        EnrollClassStudent = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cb_UserType = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jText_Username = new javax.swing.JTextField();
        jb_loginMain1 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jText_UserPassword = new javax.swing.JTextField();

        jTabbedPane_Admin.setBackground(new java.awt.Color(40, 80, 47));
        jTabbedPane_Admin.setBorder(new javax.swing.border.MatteBorder(null));

        Student.setBackground(new java.awt.Color(0, 0, 51));
        Student.setBorder(new javax.swing.border.MatteBorder(null));
        Student.setForeground(java.awt.Color.white);
        Student.setToolTipText("");

        jLabel17.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel17.setForeground(java.awt.Color.white);
        jLabel17.setText("Lastname:");

        jLabel18.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel18.setForeground(java.awt.Color.white);
        jLabel18.setText("Name:");

        jLabel19.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel19.setForeground(java.awt.Color.white);
        jLabel19.setText("ID:");

        jLabel21.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel21.setForeground(java.awt.Color.white);
        jLabel21.setText("Phone #:");

        jTable_Students.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_Students.setComponentPopupMenu(jPopup_DeleteStudent);
        jScrollPane4.setViewportView(jTable_Students);

        jLabel22.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel22.setForeground(java.awt.Color.white);
        jLabel22.setText("Address:");

        jButton_AddStudent.setBackground(new java.awt.Color(44, 44, 44));
        jButton_AddStudent.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jButton_AddStudent.setText("Add");
        jButton_AddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddStudentActionPerformed(evt);
            }
        });

        jButton_ModifyStudent.setBackground(new java.awt.Color(44, 44, 44));
        jButton_ModifyStudent.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jButton_ModifyStudent.setText("Modify");
        jButton_ModifyStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ModifyStudentActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel37.setForeground(java.awt.Color.white);
        jLabel37.setText("INPUT STUDENT ID:");

        jButton_RefreshStudent.setBackground(new java.awt.Color(44, 44, 44));
        jButton_RefreshStudent.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jButton_RefreshStudent.setText("Refresh");
        jButton_RefreshStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RefreshStudentActionPerformed(evt);
            }
        });

        jButton_SearchStudent.setBackground(new java.awt.Color(44, 44, 44));
        jButton_SearchStudent.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jButton_SearchStudent.setText("Search");
        jButton_SearchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchStudentActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Registered Students:");

        javax.swing.GroupLayout StudentLayout = new javax.swing.GroupLayout(Student);
        Student.setLayout(StudentLayout);
        StudentLayout.setHorizontalGroup(
            StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 649, Short.MAX_VALUE))
                    .addGroup(StudentLayout.createSequentialGroup()
                        .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StudentLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton_RefreshStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(StudentLayout.createSequentialGroup()
                                        .addComponent(jLabel37)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jText_StudentSearchID)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_SearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(StudentLayout.createSequentialGroup()
                                .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(StudentLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(StudentLayout.createSequentialGroup()
                                                .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel17)
                                                    .addComponent(jLabel19))
                                                .addGap(18, 18, 18)
                                                .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(StudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(StudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(StudentLastName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel18)))
                                    .addGroup(StudentLayout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(jButton_AddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(StudentLayout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(StudentAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(StudentLayout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addGap(18, 18, 18)
                                        .addComponent(StudentPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(StudentLayout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jButton_ModifyStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)))
                        .addGap(17, 17, 17))))
        );
        StudentLayout.setVerticalGroup(
            StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentLayout.createSequentialGroup()
                        .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(StudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(StudentLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)))
                    .addGroup(StudentLayout.createSequentialGroup()
                        .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StudentPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StudentAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))))
                .addGap(37, 37, 37)
                .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_AddStudent)
                    .addComponent(jButton_ModifyStudent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(StudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_StudentSearchID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_SearchStudent))
                .addGap(18, 18, 18)
                .addComponent(jButton_RefreshStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        jTabbedPane_Admin.addTab("Student", Student);

        Professor.setBackground(new java.awt.Color(0, 0, 51));
        Professor.setBorder(new javax.swing.border.MatteBorder(null));
        Professor.setForeground(java.awt.Color.white);

        jLabel46.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel46.setForeground(java.awt.Color.white);
        jLabel46.setText("Name:");

        jLabel47.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel47.setForeground(java.awt.Color.white);
        jLabel47.setText("ID:");

        jLabel48.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel48.setForeground(java.awt.Color.white);
        jLabel48.setText("Phone #:");

        jTable_AssignCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane8.setViewportView(jTable_AssignCourse);

        jLabel13.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setText("Course Type:");

        jLabel14.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel14.setForeground(java.awt.Color.white);
        jLabel14.setText("Course ID:");

        jTable_AssignCar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane9.setViewportView(jTable_AssignCar);

        jLabel42.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel42.setForeground(java.awt.Color.white);
        jLabel42.setText("INPUT  ID:");

        SearchTeacher.setBackground(new java.awt.Color(44, 44, 44));
        SearchTeacher.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        SearchTeacher.setText("Search");
        SearchTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTeacherActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel15.setForeground(java.awt.Color.white);
        jLabel15.setText("Level:");

        jLabel52.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel52.setForeground(java.awt.Color.white);
        jLabel52.setText("Course Level:");

        jLabel53.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel53.setForeground(java.awt.Color.white);
        jLabel53.setText("Kilometers:");

        jLabel54.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel54.setForeground(java.awt.Color.white);
        jLabel54.setText("Plate:");

        TeacherLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level I", "Level II", "Level III" }));

        AddTeacher.setBackground(new java.awt.Color(44, 44, 44));
        AddTeacher.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        AddTeacher.setText("Add");
        AddTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTeacherActionPerformed(evt);
            }
        });

        ModifyTeacher.setBackground(new java.awt.Color(44, 44, 44));
        ModifyTeacher.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        ModifyTeacher.setText("Modify");
        ModifyTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyTeacherActionPerformed(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel43.setForeground(java.awt.Color.white);
        jLabel43.setText("Test Type:");

        jLabel44.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel44.setForeground(java.awt.Color.white);
        jLabel44.setText("Test ID:");

        jLabel56.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel56.setForeground(java.awt.Color.white);
        jLabel56.setText("Test Level:");

        jTable_AssignTest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane10.setViewportView(jTable_AssignTest);

        AssignCar.setBackground(new java.awt.Color(44, 44, 44));
        AssignCar.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        AssignCar.setText("Assign Car");
        AssignCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignCarActionPerformed(evt);
            }
        });

        jButton_AddStudent5.setBackground(new java.awt.Color(44, 44, 44));
        jButton_AddStudent5.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jButton_AddStudent5.setText("Assign Test");
        jButton_AddStudent5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddStudent5ActionPerformed(evt);
            }
        });

        AssignCourse.setBackground(new java.awt.Color(44, 44, 44));
        AssignCourse.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        AssignCourse.setText("Assign Course");
        AssignCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignCourseActionPerformed(evt);
            }
        });

        AssignCourseLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Car", "Motrocycle", "Public Transportation", "Heavy Transportation" }));

        AssignCourseType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theorical", "Practical" }));

        AssignTestLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Car", "Motrocycle", "Public Transportation", "Heavy Transportation" }));

        AssignTestType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theorical", "Practical" }));

        javax.swing.GroupLayout ProfessorLayout = new javax.swing.GroupLayout(Professor);
        Professor.setLayout(ProfessorLayout);
        ProfessorLayout.setHorizontalGroup(
            ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfessorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfessorLayout.createSequentialGroup()
                        .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel46)
                            .addComponent(jLabel47)
                            .addComponent(jLabel48)
                            .addComponent(jLabel15))
                        .addGap(3, 3, 3)
                        .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProfessorLayout.createSequentialGroup()
                                .addComponent(TeacherLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(ProfessorLayout.createSequentialGroup()
                                .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ProfessorLayout.createSequentialGroup()
                                        .addComponent(TeacherPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ModifyTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ProfessorLayout.createSequentialGroup()
                                        .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TeacherID)
                                            .addComponent(TeacherName, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(AddTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(149, 149, 149))))
                    .addGroup(ProfessorLayout.createSequentialGroup()
                        .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(ProfessorLayout.createSequentialGroup()
                                .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                                    .addComponent(jScrollPane8))
                                .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ProfessorLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(ProfessorLayout.createSequentialGroup()
                                                .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel52)
                                                    .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel14)
                                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)))
                                                .addGap(18, 18, 18)
                                                .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(AssignCourseType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(AssignCourseID, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                                    .addComponent(AssignCourseLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(26, 26, 26))
                                            .addGroup(ProfessorLayout.createSequentialGroup()
                                                .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel53)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfessorLayout.createSequentialGroup()
                                                        .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(30, 30, 30)))
                                                .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(AssignCarPlate, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(AssigCarKilometers, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(22, 22, 22))))
                                    .addGroup(ProfessorLayout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AssignCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton_AddStudent5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(ProfessorLayout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addComponent(AssignCar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ProfessorLayout.createSequentialGroup()
                                .addComponent(jLabel42)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SearchTeacherID, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SearchTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(ProfessorLayout.createSequentialGroup()
                                .addComponent(jScrollPane10)
                                .addGap(18, 18, 18)
                                .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel56)
                                    .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel44)
                                        .addComponent(jLabel43, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(18, 18, 18)
                                .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AssignTestID, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(AssignTestType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AssignTestLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(26, 26, 26))
                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addComponent(jSeparator5)))
        );
        ProfessorLayout.setVerticalGroup(
            ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfessorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchTeacherID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchTeacher))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfessorLayout.createSequentialGroup()
                        .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel46)
                            .addComponent(TeacherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47)
                            .addComponent(TeacherID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfessorLayout.createSequentialGroup()
                        .addComponent(AddTeacher)
                        .addGap(8, 8, 8)))
                .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeacherPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48)
                    .addComponent(ModifyTeacher))
                .addGap(18, 18, 18)
                .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(TeacherLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfessorLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel54)
                            .addComponent(AssignCarPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel53)
                            .addComponent(AssigCarKilometers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(AssignCar))
                    .addGroup(ProfessorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfessorLayout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(ProfessorLayout.createSequentialGroup()
                        .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(AssignCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(AssignCourseType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel52)
                            .addComponent(AssignCourseLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(AssignCourse)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfessorLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfessorLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ProfessorLayout.createSequentialGroup()
                                .addComponent(jLabel43)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel56))
                            .addGroup(ProfessorLayout.createSequentialGroup()
                                .addGroup(ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AssignTestID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel44))
                                .addGap(18, 18, 18)
                                .addComponent(AssignTestType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AssignTestLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton_AddStudent5)
                        .addGap(40, 40, 40))))
        );

        jTabbedPane_Admin.addTab("Teacher", Professor);

        Test_Class.setBackground(new java.awt.Color(0, 0, 51));
        Test_Class.setBorder(new javax.swing.border.MatteBorder(null));
        Test_Class.setForeground(java.awt.Color.white);

        javax.swing.GroupLayout Test_ClassLayout = new javax.swing.GroupLayout(Test_Class);
        Test_Class.setLayout(Test_ClassLayout);
        Test_ClassLayout.setHorizontalGroup(
            Test_ClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 824, Short.MAX_VALUE)
        );
        Test_ClassLayout.setVerticalGroup(
            Test_ClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
        );

        jTabbedPane_Admin.addTab("More", Test_Class);

        javax.swing.GroupLayout AdministratorLayout = new javax.swing.GroupLayout(Administrator.getContentPane());
        Administrator.getContentPane().setLayout(AdministratorLayout);
        AdministratorLayout.setHorizontalGroup(
            AdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_Admin)
        );
        AdministratorLayout.setVerticalGroup(
            AdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_Admin)
        );

        jMenuItem_ViewStudent.setText("Quick View");
        jMenuItem_ViewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ViewStudentActionPerformed(evt);
            }
        });
        jPopup_DeleteStudent.add(jMenuItem_ViewStudent);

        jMenuItem_DeleteStudent.setText("DeleteEmployee");
        jMenuItem_DeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_DeleteStudentActionPerformed(evt);
            }
        });
        jPopup_DeleteStudent.add(jMenuItem_DeleteStudent);

        jMenuItem_GetData.setText("See Data");
        jMenuItem_GetData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_GetDataActionPerformed(evt);
            }
        });
        jPopupMenu_GetData.add(jMenuItem_GetData);

        jTabbedPane_Admin1.setBackground(new java.awt.Color(40, 80, 47));
        jTabbedPane_Admin1.setBorder(new javax.swing.border.MatteBorder(null));

        Student1.setBackground(new java.awt.Color(0, 0, 51));
        Student1.setBorder(new javax.swing.border.MatteBorder(null));
        Student1.setForeground(java.awt.Color.white);
        Student1.setToolTipText("");

        jLabel20.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel20.setForeground(java.awt.Color.white);
        jLabel20.setText("Lastname:");

        jLabel23.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel23.setForeground(java.awt.Color.white);
        jLabel23.setText("Name:");

        jLabel24.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel24.setForeground(java.awt.Color.white);
        jLabel24.setText("ID:");

        jLabel25.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel25.setForeground(java.awt.Color.white);
        jLabel25.setText("Phone #:");

        jTable_Classes_Students.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_Classes_Students.setComponentPopupMenu(jPopup_DeleteStudent);
        jScrollPane5.setViewportView(jTable_Classes_Students);

        jLabel26.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel26.setForeground(java.awt.Color.white);
        jLabel26.setText("Address:");

        jLabel2.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Classes:");

        jLabel3.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Licenses:");

        jTable_Licenses_Students.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_Licenses_Students.setComponentPopupMenu(jPopup_DeleteStudent);
        jScrollPane6.setViewportView(jTable_Licenses_Students);

        javax.swing.GroupLayout Student1Layout = new javax.swing.GroupLayout(Student1);
        Student1.setLayout(Student1Layout);
        Student1Layout.setHorizontalGroup(
            Student1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Student1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(Student1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator11)
                    .addGroup(Student1Layout.createSequentialGroup()
                        .addGroup(Student1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Student1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(Student1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Student1Layout.createSequentialGroup()
                                        .addGroup(Student1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel24))
                                        .addGap(18, 18, 18)
                                        .addGroup(Student1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(StudentNameStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(StudentIDStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(StudentLastNameStudent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                                .addGroup(Student1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(Student1Layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(StudentAdressStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Student1Layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addGap(18, 18, 18)
                                        .addComponent(StudentPhoneNumberStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)))
                        .addGap(17, 17, 17))
                    .addGroup(Student1Layout.createSequentialGroup()
                        .addGroup(Student1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        Student1Layout.setVerticalGroup(
            Student1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Student1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(Student1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Student1Layout.createSequentialGroup()
                        .addGroup(Student1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(StudentNameStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Student1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(StudentLastNameStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Student1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StudentIDStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)))
                    .addGroup(Student1Layout.createSequentialGroup()
                        .addGroup(Student1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StudentPhoneNumberStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Student1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StudentAdressStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        jTabbedPane_Admin1.addTab("Information", Student1);

        Professor1.setBackground(new java.awt.Color(0, 0, 51));
        Professor1.setBorder(new javax.swing.border.MatteBorder(null));
        Professor1.setForeground(java.awt.Color.white);

        jLabel55.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel55.setForeground(java.awt.Color.white);
        jLabel55.setText("Classes:");

        jLabel59.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel59.setForeground(java.awt.Color.white);
        jLabel59.setText("Test Type:");

        jLabel60.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel60.setForeground(java.awt.Color.white);
        jLabel60.setText("Test ID:");

        jLabel61.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel61.setForeground(java.awt.Color.white);
        jLabel61.setText("Test Level:");

        jTable_AssignTest1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane13.setViewportView(jTable_AssignTest1);

        jButton_AddStudent6.setBackground(new java.awt.Color(44, 44, 44));
        jButton_AddStudent6.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jButton_AddStudent6.setText("Assign Test");
        jButton_AddStudent6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddStudent6ActionPerformed(evt);
            }
        });

        AssignCourse1.setBackground(new java.awt.Color(44, 44, 44));
        AssignCourse1.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        AssignCourse1.setText("Assign Course");
        AssignCourse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignCourse1ActionPerformed(evt);
            }
        });

        AssignTestLevel1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Car", "Motrocycle", "Public Transportation", "Heavy Transportation" }));

        AssignTestType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theorical", "Practical" }));

        Combo_EnrollClasses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Automóvil y Motocicletas", "Transporte Público", "Trasporte Pesado" }));

        jLabel57.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel57.setForeground(java.awt.Color.white);
        jLabel57.setText("Teachers:");

        jLabel58.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel58.setForeground(java.awt.Color.white);
        jLabel58.setText("Cost:");

        ClassCostStudent.setEnabled(false);

        EnrollClassStudent.setText("Add Class");

        javax.swing.GroupLayout Professor1Layout = new javax.swing.GroupLayout(Professor1);
        Professor1.setLayout(Professor1Layout);
        Professor1Layout.setHorizontalGroup(
            Professor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Professor1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Professor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Professor1Layout.createSequentialGroup()
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(Professor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel61)
                            .addGroup(Professor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel60)
                                .addComponent(jLabel59, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(18, 18, 18)
                        .addGroup(Professor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AssignTestID1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(AssignTestType1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AssignTestLevel1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36))
                    .addComponent(jSeparator9)
                    .addGroup(Professor1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(Professor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AssignCourse1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_AddStudent6, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Professor1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(Professor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel55)
                                    .addComponent(jLabel57))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Professor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Combo_EnrollTeachers, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Combo_EnrollClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(108, 108, 108)
                                .addComponent(jLabel58)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ClassCostStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(Professor1Layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(EnrollClassStudent)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Professor1Layout.setVerticalGroup(
            Professor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Professor1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(Professor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ClassCostStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Professor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel58)
                        .addComponent(jLabel55)
                        .addComponent(Combo_EnrollClasses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(Professor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Combo_EnrollTeachers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel57))
                .addGap(182, 182, 182)
                .addComponent(EnrollClassStudent)
                .addGap(179, 179, 179)
                .addComponent(AssignCourse1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Professor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Professor1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Professor1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(Professor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Professor1Layout.createSequentialGroup()
                                .addComponent(jLabel59)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel61))
                            .addGroup(Professor1Layout.createSequentialGroup()
                                .addGroup(Professor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AssignTestID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel60))
                                .addGap(18, 18, 18)
                                .addComponent(AssignTestType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AssignTestLevel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton_AddStudent6)
                        .addGap(40, 40, 40))))
        );

        jTabbedPane_Admin1.addTab("Enroll Classes", Professor1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 826, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
        );

        jTabbedPane_Admin1.addTab("Costs", jPanel1);

        javax.swing.GroupLayout StudentJFrameLayout = new javax.swing.GroupLayout(StudentJFrame.getContentPane());
        StudentJFrame.getContentPane().setLayout(StudentJFrameLayout);
        StudentJFrameLayout.setHorizontalGroup(
            StudentJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_Admin1)
        );
        StudentJFrameLayout.setVerticalGroup(
            StudentJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_Admin1)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        cb_UserType.setFont(new java.awt.Font("TlwgTypewriter", 0, 15)); // NOI18N
        cb_UserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrator", "Student", "Teacher" }));

        jLabel8.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("User Type: ");

        jLabel9.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Username:");

        jLabel10.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Password:");

        jb_loginMain1.setBackground(new java.awt.Color(44, 44, 44));
        jb_loginMain1.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        jb_loginMain1.setText("Login");
        jb_loginMain1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_loginMain1ActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel27.setForeground(java.awt.Color.white);
        jLabel27.setText("NOTE: *Student login requires a registered account.");

        jLabel28.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel28.setForeground(java.awt.Color.white);
        jLabel28.setText("*Teacher login requires password granted by local admin.");

        jLabel34.setFont(new java.awt.Font("TlwgTypewriter", 1, 24)); // NOI18N
        jLabel34.setForeground(java.awt.Color.white);
        jLabel34.setText("General Login");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel34))
                    .addComponent(jLabel28)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel27)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jb_loginMain1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jText_UserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(23, 23, 23)
                                            .addComponent(jText_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addComponent(cb_UserType, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(11, 11, 11))))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cb_UserType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jText_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jText_UserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_loginMain1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_loginMain1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_loginMain1ActionPerformed
        String UserType = (String) cb_UserType.getSelectedItem();
        String UserName = jText_Username.getText();
        String Password = jText_UserPassword.getText();
        if (DB.VerifyUser(UserName,Password)=="Wrong User") {
            String tipo = "";
            if (UserType.equals("Administrator")) {
                Administrator.setVisible(true);
                Administrator.pack();
            }else if (UserType.equals("Student")) {
                
            }else{
                
            }
       
        } else {
            JOptionPane.showMessageDialog(this, "Incorrect Password or Username");
        }
            
    }//GEN-LAST:event_jb_loginMain1ActionPerformed

    private void jButton_RefreshStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RefreshStudentActionPerformed
        DefaultTableModel Modelo = new DefaultTableModel();
        Modelo.addColumn("ID");
        Modelo.addColumn("Name");
        Modelo.addColumn("LastName");
        Modelo.addColumn("PhoneNumber");
        Modelo.addColumn("Student Adress");
        jTable_Students.setModel(DB.GetAllStudentDocuments(Modelo));
    }//GEN-LAST:event_jButton_RefreshStudentActionPerformed

    private void jButton_SearchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchStudentActionPerformed
       
    }//GEN-LAST:event_jButton_SearchStudentActionPerformed

    private void SearchTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTeacherActionPerformed
        DefaultTableModel Modelo = new DefaultTableModel();
        //Cars
        Modelo.addColumn("Plate");
        Modelo.addColumn("Kilometers");
        jTable_AssignCar.setModel(DB.GetCarDocuments(Modelo));
        //Courses
        Modelo = new DefaultTableModel();
        Modelo.addColumn("CourseID");
        Modelo.addColumn("Type");
        Modelo.addColumn("Level");
        Modelo.addColumn("Duration");
        jTable_AssignCourse.setModel(DB.GetCourseDocuments(Modelo));
        //Tests
        Modelo = new DefaultTableModel();
        Modelo.addColumn("TestID");
        Modelo.addColumn("Type");
        Modelo.addColumn("Level");
        jTable_AssignTest.setModel(DB.GetTestDocuments(Modelo));
        
    }//GEN-LAST:event_SearchTeacherActionPerformed

    private void jMenuItem_ViewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ViewStudentActionPerformed
        
    }//GEN-LAST:event_jMenuItem_ViewStudentActionPerformed

    private void jMenuItem_DeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_DeleteStudentActionPerformed
        int Row=jTable_Students.getSelectedRow();                
        String IDtoErase=jTable_Students.getValueAt(Row,0).toString();
        DB.DeleteStudentDocument(IDtoErase);
        JOptionPane.showMessageDialog(this, "Stundent Deleted Successfully!");
    }//GEN-LAST:event_jMenuItem_DeleteStudentActionPerformed

    private void jMenuItem_GetDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_GetDataActionPerformed
      
    }//GEN-LAST:event_jMenuItem_GetDataActionPerformed

    private void AddTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTeacherActionPerformed
        DB.AddTeacherDocument(TeacherID.getText(),TeacherName.getText(),TeacherPhoneNumber.getText(),TeacherLevel.getSelectedItem().toString());
        JOptionPane.showMessageDialog(this, "New Teacher Created Successfully!");
    }//GEN-LAST:event_AddTeacherActionPerformed

    private void ModifyTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyTeacherActionPerformed
        DB.ModifyTeacherDocument(TeacherID.getText(),TeacherName.getText(),TeacherPhoneNumber.getText(),TeacherLevel.getSelectedItem().toString());
        JOptionPane.showMessageDialog(this, "Teacher Modified Correctly!");
    }//GEN-LAST:event_ModifyTeacherActionPerformed

    private void AssignCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AssignCarActionPerformed

    private void jButton_AddStudent5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddStudent5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_AddStudent5ActionPerformed

    private void AssignCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AssignCourseActionPerformed

    private void jButton_ModifyStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ModifyStudentActionPerformed
        DB.ModifyStudentDocument(StudentID.getText(),StudentName.getText(),StudentLastName.getText(),StudentPhoneNumber.getText(),StudentAdress.getText());
        JOptionPane.showMessageDialog(this, "Stundent Modified Successfully!");
    }//GEN-LAST:event_jButton_ModifyStudentActionPerformed

    private void jButton_AddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddStudentActionPerformed
        DB.AddStudentDocument(StudentID.getText(),StudentName.getText(),StudentLastName.getText(),StudentPhoneNumber.getText(),StudentAdress.getText());
        JOptionPane.showMessageDialog(this, "Stundent Created Successfully!");
    }//GEN-LAST:event_jButton_AddStudentActionPerformed

    private void AssignCourse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignCourse1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AssignCourse1ActionPerformed

    private void jButton_AddStudent6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddStudent6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_AddStudent6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTeacher;
    private javax.swing.JFrame Administrator;
    private javax.swing.JTextField AssigCarKilometers;
    private javax.swing.JButton AssignCar;
    private javax.swing.JTextField AssignCarPlate;
    private javax.swing.JButton AssignCourse;
    private javax.swing.JButton AssignCourse1;
    private javax.swing.JTextField AssignCourseID;
    private javax.swing.JComboBox<String> AssignCourseLevel;
    private javax.swing.JComboBox<String> AssignCourseType;
    private javax.swing.JTextField AssignTestID;
    private javax.swing.JTextField AssignTestID1;
    private javax.swing.JComboBox<String> AssignTestLevel;
    private javax.swing.JComboBox<String> AssignTestLevel1;
    private javax.swing.JComboBox<String> AssignTestType;
    private javax.swing.JComboBox<String> AssignTestType1;
    private javax.swing.JTextField ClassCostStudent;
    private javax.swing.JComboBox<String> Combo_EnrollClasses;
    private javax.swing.JComboBox<String> Combo_EnrollTeachers;
    private javax.swing.JButton EnrollClassStudent;
    private javax.swing.JButton ModifyTeacher;
    private javax.swing.JPanel Professor;
    private javax.swing.JPanel Professor1;
    private javax.swing.JButton SearchTeacher;
    private javax.swing.JTextField SearchTeacherID;
    private javax.swing.JPanel Student;
    private javax.swing.JPanel Student1;
    private javax.swing.JTextField StudentAdress;
    private javax.swing.JTextField StudentAdressStudent;
    private javax.swing.JTextField StudentID;
    private javax.swing.JTextField StudentIDStudent;
    private javax.swing.JFrame StudentJFrame;
    private javax.swing.JTextField StudentLastName;
    private javax.swing.JTextField StudentLastNameStudent;
    private javax.swing.JTextField StudentName;
    private javax.swing.JTextField StudentNameStudent;
    private javax.swing.JTextField StudentPhoneNumber;
    private javax.swing.JTextField StudentPhoneNumberStudent;
    private javax.swing.JTextField TeacherID;
    private javax.swing.JComboBox<String> TeacherLevel;
    private javax.swing.JTextField TeacherName;
    private javax.swing.JTextField TeacherPhoneNumber;
    private javax.swing.JPanel Test_Class;
    private javax.swing.JComboBox<String> cb_UserType;
    private javax.swing.JButton jButton_AddStudent;
    private javax.swing.JButton jButton_AddStudent5;
    private javax.swing.JButton jButton_AddStudent6;
    private javax.swing.JButton jButton_ModifyStudent;
    private javax.swing.JButton jButton_RefreshStudent;
    private javax.swing.JButton jButton_SearchStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem_DeleteStudent;
    private javax.swing.JMenuItem jMenuItem_GetData;
    private javax.swing.JMenuItem jMenuItem_ViewStudent;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu_GetData;
    private javax.swing.JPopupMenu jPopup_DeleteStudent;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane_Admin;
    private javax.swing.JTabbedPane jTabbedPane_Admin1;
    private javax.swing.JTable jTable_AssignCar;
    private javax.swing.JTable jTable_AssignCourse;
    private javax.swing.JTable jTable_AssignTest;
    private javax.swing.JTable jTable_AssignTest1;
    private javax.swing.JTable jTable_Classes_Students;
    private javax.swing.JTable jTable_Licenses_Students;
    private javax.swing.JTable jTable_Students;
    private javax.swing.JTextField jText_StudentSearchID;
    private javax.swing.JTextField jText_UserPassword;
    private javax.swing.JTextField jText_Username;
    private javax.swing.JButton jb_loginMain1;
    // End of variables declaration//GEN-END:variables
    String AdminUsername="Juana";
    String AdminPassword="123";
    ConnectToDB DB=new ConnectToDB();
        
}
